version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  default:
    name: signup-network
