services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: signupdb
      POSTGRES_USER: signupuser
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U signupuser -d signupdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: sh -c "sleep 10 && pnpm prisma migrate deploy && pnpm start"

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
