version: '3.8'

services:
  # Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: signupdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      target: production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "sleep 10 && pnpm prisma migrate deploy && pnpm start"

  # Frontend
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: